apiVersion: v1
kind: Service
metadata:
  name: qrcode-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: NodePort
  selector:
    app: qrcode-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080