apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: twitter-app
  template:
    metadata:
      labels:
        app: twitter-app
    spec:
      containers:
      - name: twitter-app
        image: 851725245278.dkr.ecr.us-east-1.amazonaws.com/twitter-ecr:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: twitter-config

# ---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: twitter-autoscaling
#   namespace: default
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: twitter-deployment
#   minReplicas: 6
#   maxReplicas: 6
#   targetCPUUtilizationPercentage: 50